system:
  random_seed: 8
  num_gpus: 1
  port: 12355
note: ""
exp_name: ""
exp_directory: snorm_exps
batch_size: 8
train_first_view_only: False  # Train only on first view (useful for testing coordinate system alignment)
#concat_with_base: True
defaults:
  - optimizer: ten_epoch
  - dataset: navi
  - probe: snorm_dpt
  - _self_